# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/renan/iccad2016uffs

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/renan/iccad2016uffs

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/renan/iccad2016uffs/CMakeFiles /home/renan/iccad2016uffs/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/renan/iccad2016uffs/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rapidcheck

# Build rule for target.
rapidcheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rapidcheck
.PHONY : rapidcheck

# fast build rule for target.
rapidcheck/fast:
	$(MAKE) -f ext-lib/rapidcheck/CMakeFiles/rapidcheck.dir/build.make ext-lib/rapidcheck/CMakeFiles/rapidcheck.dir/build
.PHONY : rapidcheck/fast

#=============================================================================
# Target rules for targets named verilog_model

# Build rule for target.
verilog_model: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 verilog_model
.PHONY : verilog_model

# fast build rule for target.
verilog_model/fast:
	$(MAKE) -f lib/CMakeFiles/verilog_model.dir/build.make lib/CMakeFiles/verilog_model.dir/build
.PHONY : verilog_model/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) -f test/CMakeFiles/ExperimentalBuild.dir/build.make test/CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) -f test/CMakeFiles/ContinuousUpdate.dir/build.make test/CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) -f test/CMakeFiles/ExperimentalStart.dir/build.make test/CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) -f test/CMakeFiles/Nightly.dir/build.make test/CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) -f test/CMakeFiles/ContinuousCoverage.dir/build.make test/CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) -f test/CMakeFiles/ContinuousStart.dir/build.make test/CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) -f test/CMakeFiles/ExperimentalCoverage.dir/build.make test/CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) -f test/CMakeFiles/NightlyConfigure.dir/build.make test/CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) -f test/CMakeFiles/NightlyCoverage.dir/build.make test/CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) -f test/CMakeFiles/NightlyTest.dir/build.make test/CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named simulation.x

# Build rule for target.
simulation.x: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simulation.x
.PHONY : simulation.x

# fast build rule for target.
simulation.x/fast:
	$(MAKE) -f test/CMakeFiles/simulation.x.dir/build.make test/CMakeFiles/simulation.x.dir/build
.PHONY : simulation.x/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) -f test/CMakeFiles/Experimental.dir/build.make test/CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named TestBDD.x

# Build rule for target.
TestBDD.x: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestBDD.x
.PHONY : TestBDD.x

# fast build rule for target.
TestBDD.x/fast:
	$(MAKE) -f test/CMakeFiles/TestBDD.x.dir/build.make test/CMakeFiles/TestBDD.x.dir/build
.PHONY : TestBDD.x/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) -f test/CMakeFiles/Continuous.dir/build.make test/CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) -f test/CMakeFiles/ContinuousBuild.dir/build.make test/CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) -f test/CMakeFiles/ExperimentalUpdate.dir/build.make test/CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) -f test/CMakeFiles/ContinuousTest.dir/build.make test/CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) -f test/CMakeFiles/NightlySubmit.dir/build.make test/CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) -f test/CMakeFiles/NightlyBuild.dir/build.make test/CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named TestSpirit1.x

# Build rule for target.
TestSpirit1.x: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestSpirit1.x
.PHONY : TestSpirit1.x

# fast build rule for target.
TestSpirit1.x/fast:
	$(MAKE) -f test/CMakeFiles/TestSpirit1.x.dir/build.make test/CMakeFiles/TestSpirit1.x.dir/build
.PHONY : TestSpirit1.x/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) -f test/CMakeFiles/NightlyMemoryCheck.dir/build.make test/CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) -f test/CMakeFiles/NightlyStart.dir/build.make test/CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) -f test/CMakeFiles/NightlyUpdate.dir/build.make test/CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named TestConvert1.x

# Build rule for target.
TestConvert1.x: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestConvert1.x
.PHONY : TestConvert1.x

# fast build rule for target.
TestConvert1.x/fast:
	$(MAKE) -f test/CMakeFiles/TestConvert1.x.dir/build.make test/CMakeFiles/TestConvert1.x.dir/build
.PHONY : TestConvert1.x/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) -f test/CMakeFiles/ExperimentalTest.dir/build.make test/CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named TestSimulateIcarus.x

# Build rule for target.
TestSimulateIcarus.x: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestSimulateIcarus.x
.PHONY : TestSimulateIcarus.x

# fast build rule for target.
TestSimulateIcarus.x/fast:
	$(MAKE) -f test/CMakeFiles/TestSimulateIcarus.x.dir/build.make test/CMakeFiles/TestSimulateIcarus.x.dir/build
.PHONY : TestSimulateIcarus.x/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) -f test/CMakeFiles/ExperimentalMemCheck.dir/build.make test/CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) -f test/CMakeFiles/NightlyMemCheck.dir/build.make test/CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) -f test/CMakeFiles/ExperimentalSubmit.dir/build.make test/CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named TestSimulateGraph.x

# Build rule for target.
TestSimulateGraph.x: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestSimulateGraph.x
.PHONY : TestSimulateGraph.x

# fast build rule for target.
TestSimulateGraph.x/fast:
	$(MAKE) -f test/CMakeFiles/TestSimulateGraph.x.dir/build.make test/CMakeFiles/TestSimulateGraph.x.dir/build
.PHONY : TestSimulateGraph.x/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) -f test/CMakeFiles/ContinuousConfigure.dir/build.make test/CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) -f test/CMakeFiles/ContinuousMemCheck.dir/build.make test/CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) -f test/CMakeFiles/ExperimentalConfigure.dir/build.make test/CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named TestRapidCheck.x

# Build rule for target.
TestRapidCheck.x: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestRapidCheck.x
.PHONY : TestRapidCheck.x

# fast build rule for target.
TestRapidCheck.x/fast:
	$(MAKE) -f test/CMakeFiles/TestRapidCheck.x.dir/build.make test/CMakeFiles/TestRapidCheck.x.dir/build
.PHONY : TestRapidCheck.x/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) -f test/CMakeFiles/ContinuousSubmit.dir/build.make test/CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named TestParser1.x

# Build rule for target.
TestParser1.x: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestParser1.x
.PHONY : TestParser1.x

# fast build rule for target.
TestParser1.x/fast:
	$(MAKE) -f test/CMakeFiles/TestParser1.x.dir/build.make test/CMakeFiles/TestParser1.x.dir/build
.PHONY : TestParser1.x/fast

#=============================================================================
# Target rules for targets named aleatory_simulate_graph.x

# Build rule for target.
aleatory_simulate_graph.x: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 aleatory_simulate_graph.x
.PHONY : aleatory_simulate_graph.x

# fast build rule for target.
aleatory_simulate_graph.x/fast:
	$(MAKE) -f app/CMakeFiles/aleatory_simulate_graph.x.dir/build.make app/CMakeFiles/aleatory_simulate_graph.x.dir/build
.PHONY : aleatory_simulate_graph.x/fast

#=============================================================================
# Target rules for targets named iccad2016solve.x

# Build rule for target.
iccad2016solve.x: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iccad2016solve.x
.PHONY : iccad2016solve.x

# fast build rule for target.
iccad2016solve.x/fast:
	$(MAKE) -f app/CMakeFiles/iccad2016solve.x.dir/build.make app/CMakeFiles/iccad2016solve.x.dir/build
.PHONY : iccad2016solve.x/fast

#=============================================================================
# Target rules for targets named verilog_parser

# Build rule for target.
verilog_parser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 verilog_parser
.PHONY : verilog_parser

# fast build rule for target.
verilog_parser/fast:
	$(MAKE) -f app/CMakeFiles/verilog_parser.dir/build.make app/CMakeFiles/verilog_parser.dir/build
.PHONY : verilog_parser/fast

#=============================================================================
# Target rules for targets named TestParser_fields.x

# Build rule for target.
TestParser_fields.x: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestParser_fields.x
.PHONY : TestParser_fields.x

# fast build rule for target.
TestParser_fields.x/fast:
	$(MAKE) -f app/CMakeFiles/TestParser_fields.x.dir/build.make app/CMakeFiles/TestParser_fields.x.dir/build
.PHONY : TestParser_fields.x/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... rapidcheck"
	@echo "... verilog_model"
	@echo "... ExperimentalBuild"
	@echo "... ContinuousUpdate"
	@echo "... ExperimentalStart"
	@echo "... Nightly"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousStart"
	@echo "... ExperimentalCoverage"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyTest"
	@echo "... simulation.x"
	@echo "... Experimental"
	@echo "... TestBDD.x"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ExperimentalUpdate"
	@echo "... ContinuousTest"
	@echo "... NightlySubmit"
	@echo "... NightlyBuild"
	@echo "... TestSpirit1.x"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlyUpdate"
	@echo "... TestConvert1.x"
	@echo "... ExperimentalTest"
	@echo "... TestSimulateIcarus.x"
	@echo "... ExperimentalMemCheck"
	@echo "... NightlyMemCheck"
	@echo "... ExperimentalSubmit"
	@echo "... TestSimulateGraph.x"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousMemCheck"
	@echo "... ExperimentalConfigure"
	@echo "... TestRapidCheck.x"
	@echo "... ContinuousSubmit"
	@echo "... TestParser1.x"
	@echo "... aleatory_simulate_graph.x"
	@echo "... iccad2016solve.x"
	@echo "... verilog_parser"
	@echo "... TestParser_fields.x"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

